<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index']);
Route::get('/chatbot', [HomeController::class, 'chatbot'])->name('chatbot');
Route::post('/chatbot/ask', [HomeController::class, 'chatbotAsk'])->name('chatbot.ask');
Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
Route::get('/dashboard/data-blok', [HomeController::class, 'dataBlok'])->name('dashboard.data-blok');
Route::get('/dashboard/data-plot', [HomeController::class, 'dataPlot'])->name('dashboard.data-plot');
Route::get('/dashboard/data-almarhum', [HomeController::class, 'dataAlmarhum'])->name('dashboard.data-almarhum');
Route::get('/dashboard/data-kontak-keluarga', [HomeController::class, 'dataKontakKeluarga'])->name('dashboard.data-kontak-keluarga');
Route::post('/dashboard/data-kontak-keluarga', [HomeController::class, 'storeDataKontakKeluarga'])->name('dashboard.data-kontak-keluarga.store');
Route::delete('/dashboard/data-kontak-keluarga/{familyid}', [HomeController::class, 'destroyDataKontakKeluarga'])->name('dashboard.data-kontak-keluarga.destroy');
Route::post('/dashboard/data-almarhum', [HomeController::class, 'storeDataAlmarhum'])->name('dashboard.data-almarhum.store');
Route::put('/dashboard/data-almarhum/{deceased}', [HomeController::class, 'updateDataAlmarhum'])->name('dashboard.data-almarhum.update');
Route::delete('/dashboard/data-almarhum/{deceased}', [HomeController::class, 'destroyDataAlmarhum'])->name('dashboard.data-almarhum.destroy');
Route::get('/dashboard/data-user', [HomeController::class, 'dataUser'])->name('dashboard.data-user');
Route::get('/dashboard/activity-log', [HomeController::class, 'activityLog'])->name('dashboard.activity-log');
Route::get('/dashboard/restore-data', [HomeController::class, 'restoreData'])->name('dashboard.restore-data');
Route::post('/dashboard/restore-data/{restoreid}/restore', [HomeController::class, 'restoreDataItem'])->name('dashboard.restore-data.restore');
Route::delete('/dashboard/restore-data/{restoreid}/force-delete', [HomeController::class, 'forceDeleteRestoreDataItem'])->name('dashboard.restore-data.force-delete');
Route::get('/dashboard/hak-akses', [HomeController::class, 'hakAkses'])->name('dashboard.hak-akses');
Route::post('/dashboard/hak-akses', [HomeController::class, 'updateHakAkses'])->name('dashboard.hak-akses.update');
Route::post('/dashboard/data-user', [HomeController::class, 'storeUser'])->name('dashboard.data-user.store');
Route::post('/dashboard/data-user/{user}/reset-password', [HomeController::class, 'resetUserPassword'])->name('dashboard.data-user.reset-password');
Route::delete('/dashboard/data-user/{user}', [HomeController::class, 'destroyUser'])->name('dashboard.data-user.destroy');
Route::post('/dashboard/data-plot', [HomeController::class, 'storeDataPlot'])->name('dashboard.data-plot.store');
Route::put('/dashboard/data-plot/{plot}', [HomeController::class, 'updateDataPlot'])->name('dashboard.data-plot.update');
Route::delete('/dashboard/data-plot/{plot}', [HomeController::class, 'destroyDataPlot'])->name('dashboard.data-plot.destroy');
Route::post('/dashboard/data-blok', [HomeController::class, 'storeDataBlok'])->name('dashboard.data-blok.store');
Route::put('/dashboard/data-blok/{block}', [HomeController::class, 'updateDataBlok'])->name('dashboard.data-blok.update');
Route::post('/dashboard/data-blok/positions', [HomeController::class, 'updateDataBlokPositions'])->name('dashboard.data-blok.positions');
Route::delete('/dashboard/data-blok/{block}', [HomeController::class, 'destroyDataBlok'])->name('dashboard.data-blok.destroy');
Route::get('/dashboard/pengaturan', [HomeController::class, 'websiteSettings'])->name('dashboard.settings');
Route::post('/dashboard/pengaturan', [HomeController::class, 'updateWebsiteSettings'])->name('dashboard.settings.update');
Route::get('/dashboard/akun', [HomeController::class, 'accountSettings'])->name('dashboard.account');
Route::post('/dashboard/akun', [HomeController::class, 'updateAccountSettings'])->name('dashboard.account.update');
Route::post('/dashboard/akun/password', [HomeController::class, 'updateAccountPassword'])->name('dashboard.account.password');
Route::get('/deceased/{id}', [HomeController::class, 'deceasedDetail'])->name('deceased.detail');
Route::get('/media/deceased-photo', [HomeController::class, 'serveDeceasedPhoto'])->name('media.deceased-photo');
Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login.submit');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
